version: "3.8"
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: orders
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  order-microservice:
    build:
      context: ./order-microservice
      dockerfile: Dockerfile
    container_name: order-microservice
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/orders
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  payment-microservice:
    build:
      context: ./payment-microservice
      dockerfile: Dockerfile
    container_name: paymentr-microservice
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081

volumes:
  mysql-data:
    name: orders-mysql-data
