events {
    worker_connections 10240;  
    multi_accept on; 
    use epoll;  
}


http {

    sendfile on;  # Habilita envío de archivos eficiente
    tcp_nopush on;  # Optimiza la transmisión de datos
    tcp_nodelay on;  # Reduce la latencia en paquetes pequeños
    keepalive_timeout 65;  # Tiempo de espera para mantener conexiones abiertas
    client_body_buffer_size 10M;  # Buffer para manejar grandes requests
    client_max_body_size 100M;  # Tamaño máximo de request (ajustar según necesidad)

    log_format json_logs '{'
                     '"time": "$time_iso8601",'
                     '"remote_addr": "$remote_addr",'
                     '"request": "$request",'
                     '"status": "$status",'
                     '"body_bytes_sent": "$body_bytes_sent",'
                     '"request_time": "$request_time"'
                     '}';

    access_log /var/log/nginx/access.log json_logs;
    error_log /var/log/nginx/error.log warn;


    upstream order_service {
        server order:8080 max_fails=1 fail_timeout=0;  # Si falla 1 vez en 1s, se considera fuera de servicio
    }

    server {
        listen 80;

        location /orders {
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_next_upstream off;  # No reintentar con otro servidor
            proxy_connect_timeout 1s; # Tiempo para conectar (pero no afecta la disponibilidad)
            proxy_send_timeout 1s;
            proxy_read_timeout 1s;

            # Cuando el upstream está caído, responde con 503 inmediatamente
            error_page 502 503 504 =503 /custom_503.html;
        }

        location = /custom_503.html {
            internal;
            default_type text/html;
            return 503 "Service Unavailable - O serviço de pedidos está fora do ar.";
        }
    }

    server {
        listen 9114;

        location /metrics {
            stub_status on;
            allow all;
            access_log off;  # Desactiva logs de acceso para mejorar rendimiento

        }
    }
}
