global:
  scrape_interval: 15s # Intervalo padrão para coleta de métricas

scrape_configs:
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order:8080'] # Serviço Order

  - job_name: 'payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment:8081'] # Serviço Payment
